---
- name: get cryptdevice uuid
  command: blkid -s UUID -o value "{{ boot_encryption.cryptdevice }}"
  changed_when: false
  become: true
  register: cryptdevice_uuid
  tags: grub,dm-crypt

- name: set kernel cmdline
  set_fact:
    grub_boot_options:
      - "cryptdevice=UUID={{ cryptdevice_uuid.stdout }}:lvm"
      - "root={{ boot_encryption.rootdevice }}"
  become: false
  tags: grub,dm-crypt

- name: setup luks keyfile
  command: dd bs=512 count=4 if=/dev/urandom of=/crypto_keyfile.bin
  args:
    creates: /crypto_keyfile.bin
  become: true
  tags: grub,dm-crypt

- name: set secure permissions
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
  with_items: "{{ grub_secure_files }}"
  become: true
  tags: grub,dm-crypt
