---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  become: false
  tags: grub,dm-crypt

- name: enable intel microcode updates
  package:
    name: "{{ intel_ucode_pkg_name }}"
    state: present
  args:
    update_cache: true
  notify: update config
  when: "'GenuineIntel' in ansible_processor"
  become: true
  tags: grub

- name: setup disk encryption
  include: crypt.yml
  when: boot_encryption.enabled
  become: false
  tags: grub,dm-crypt

- name: append boot_options
  set_fact:
    grub_boot_options: "{{ grub_boot_options }} + {{ boot_options }}"
  when: boot_options is defined
  become: false
  tags: grub,dm-crypt

- name: setup grub defaults
  template:
    src: grub.j2
    dest: /etc/default/grub
    mode: 0644
  notify: update config
  become: true
  tags: grub,dm-crypt

- name: install grub
  package:
    name: "{{ grub_pkg_name }}"
    state: present
  args:
    update_cache: true
  notify:
    - install to disk
    - update config
  become: true
  tags: grub
