---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: grub,dm-crypt

- name: enable intel microcode updates
  package:
    name: "{{ intel_ucode_pkg_name }}"
    state: present
  args:
    update_cache: true
  notify: update config
  when: "'GenuineIntel' in ansible_processor"
  become: true
  tags: grub

- name: set grub_target
  set_fact:
    grub_target: "--target=i386-pc"
  tags: grub

- name: setup disk encryption
  include: crypt.yml
  when: boot_encryption.enabled
  tags: grub,dm-crypt

- name: install grub
  package:
    name: "{{ grub_pkg_name }}"
    state: present
  args:
    update_cache: true
  notify:
    - install to disk
    - update config
  become: true
  tags: grub
