---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: grub

- name: enable intel microcode updates
  package:
    name: "{{ intel_ucode_pkg_name }}"
    state: present
  args:
    update_cache: true
  notify: update config
  when: "'GenuineIntel' in ansible_processor"
  become: true
  tags: grub

- name: install grub
  package:
    name: "{{ grub_pkg_name }}"
    state: present
  args:
    update_cache: true
  notify:
    - install to disk
    - update config
  when: ansible_architecture == 'x86'
  become: true
  tags: grub
